name: Module Twitch

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  module-twitch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install wine
        run: sudo apt install wine wine64

      - name: Build
        run: |
          yarn
          yarn build:x64

      - name: Pack Linux x64
        run: |
          cd build/linux-x64
          npx bestzip ../../twitch-linux-x64.zip .

      - name: Pack Win x64
        run: |
          cd build/win-x64
          npx bestzip ../../twitch-win-x64.zip .

      - name: Pack Linux x64
        run: |
          cd build/macos-x64
          npx bestzip ../../twitch-macos-x64.zip .

      - name: Artefact Macos x64
        uses: actions/upload-artifact@v2
        if: !(startsWith(github.ref, 'refs/tags/'))
        with:
          name: twitch-macos-x64
          path: ./twitch-macos-x64.zip

      - name: Artefact Linux x64
        uses: actions/upload-artifact@v2
        if: !(startsWith(github.ref, 'refs/tags/'))
        with:
          name: twitch-linux x64
          path: ./twitch-linux-x64.zip

      - name: Artefact Win x64
        uses: actions/upload-artifact@v2
        if: !(startsWith(github.ref, 'refs/tags/'))
        with:
          name: twitch-win-x64
          path: ./twitch-win-x64.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.zip
